<template><div><h2 id="组件列表" tabindex="-1"><a class="header-anchor" href="#组件列表" aria-hidden="true">#</a> 组件列表</h2>
<table>
<thead>
<tr>
<th>组件</th>
<th>描述</th>
<th>源码</th>
</tr>
</thead>
<tbody>
<tr>
<td>table-pro</td>
<td>高级表格，自动生成上方的搜索栏，上方常用工具栏，以及翻页等功能的便捷封装。</td>
<td><a href="">github</a>,<a href="https://gitee.com/archyInk/ant-design-vue-pro/blob/master/components/tablePro/tablePro.tsx" target="_blank" rel="noopener noreferrer">gitee<ExternalLinkIcon/></a></td>
</tr>
<tr>
<td>form-pro</td>
<td>高级表单，表单和grid的合并，能够方便排列。</td>
<td><a href="">github</a>,<a href="https://gitee.com/archyInk/ant-design-vue-pro/blob/master/components/formPro/formPro.tsx" target="_blank" rel="noopener noreferrer">gitee<ExternalLinkIcon/></a></td>
</tr>
<tr>
<td>modal-pro</td>
<td>高级浮层，能够移动并全屏。</td>
<td>未完成</td>
</tr>
<tr>
<td>water-mark</td>
<td>水印组件。</td>
<td>未完成</td>
</tr>
<tr>
<td>image-zoom</td>
<td>带放大镜的图片。</td>
<td>未完成</td>
</tr>
<tr>
<td>check-card</td>
<td>能够选择的卡片。</td>
<td>未完成</td>
</tr>
<tr>
<td>image-thumb</td>
<td>缩略图图片。</td>
<td>未完成</td>
</tr>
<tr>
<td>select-pro</td>
<td>高级选择框，能够快速生成筛选选择框。</td>
<td>未完成</td>
</tr>
<tr>
<td>select-table</td>
<td>高级选择框，下拉框带表格。</td>
<td>未完成</td>
</tr>
<tr>
<td>list-pro</td>
<td>高级列表。</td>
<td>未完成</td>
</tr>
</tbody>
</table>
</div></template>
